config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes, only: [:new, :create, :index, :show, :destroy, :put] do
    resources :recipe_foods, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :foods, only: [:index, :new, :create, :destroy]
  get 'public_recipes', to: 'recipes#public_recipes'

  get 'shopping_list', to: 'shopping_list#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  match 'recipes/:recipe_id' => 'recipes#toggle_public', as: :toggle_public, via: :patch

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, RecipeFood, user_id: user.id
    can :manage, Food, user_id: user.id

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def total_quantity_recipes
    recipe_foods.map { |recipe_food| recipe_food.quantity.to_i }.sum
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  def total_price
    foods.map { |f| f.price * f.recipe_foods.find_by(recipe_id: id).quantity }.sum
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @current_user = current_user
    @foods = current_user.foods
  end

  def new
    @current_user = current_user
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    if @food.save
      redirect_to foods_path, notice: 'Your Food is created successfully 💯'
    else
      flash[:alert] = 'Something went wrong, Try again!'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @current_user = current_user
    @recipe = Recipe.find_by_id(params[:recipe_id])
    @available_foods = current_user.foods.reject { |f| @recipe.foods.include?(f) }
    @ingredient = RecipeFood.new
  end

  def create
    @recipe = Recipe.find_by_id(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params.merge(recipe_id: @recipe.id))
    if @recipe_food.save
      redirect_to recipe_path(@recipe.id)
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.update(quantity: params[:recipe_food][:quantity])

    if @recipe_food.save
      redirect_to recipe_path(params[:recipe_id]), notice: 'Your quantity updated successfully'
    else
      flash[:alert] = 'something went wrong, try again!!'
      render :edit
    end
  end

  def destroy
    @recipe_food = RecipeFood.find_by_id(params[:id])
    if @recipe_food.destroy
      flash[:noticw] = 'Ingedient deleted.'
    else
      flash[:alert] = 'Ingedient deletion unsucessful.'
    end
    redirect_to recipe_path(params[:recipe_id])
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
    @current_user = current_user
  end

  def create
    @current_user = current_user
    @recipe = Recipe.new(recipe_params.merge(user_id: @current_user.id))

    if @recipe.save
      redirect_to recipes_path, notice: 'Your Recipe is created successfully 🎉'
    else
      flash[:alert] = 'Something went wrong, try again!!'
      redirect_to recipes_path
    end
  end

  def index
    @current_user = current_user

    if @current_user
      @recipes = @current_user.recipes
    else
      # Handle the case where the user is not logged in
      flash[:alert] = 'Please log in to view your recipes.'
      redirect_to new_user_session_path
    end
  end

  def show
    @current_user = current_user
    @recipe = Recipe.find_by_id(params[:id])
    @ingredients = @recipe&.recipe_foods
  end

  def toggle_public
    @recipe = Recipe.find_by_id(params[:recipe_id])
    @recipe.public = !@recipe.public

    redirect_to recipe_path(@recipe.id), notice: 'Recipe updated' if @recipe.save
  end

  def public_recipes
    @current_user = current_user
    @recipes = Recipe.where(public: true)
  end

  def destroy
    @recipe = Recipe.find_by_id(params[:id])
    redirect_to recipes_path if @recipe.destroy
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @current_user = current_user
    @foods = current_user.recipes.includes(:foods).map(&:foods).flatten.uniq
    @total_quantity = @foods.sum(&:total_quantity_recipes)
    @total_price = @foods.sum { |food| food.price * food.total_quantity_recipes }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div class="table-responsive mt-4">
  <div class="d-flex justify-content-end">
    <%= link_to "Add food", "foods/new", class: "btn btn-success"%>
  </div>
  <table class="table table-light table-bordered mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement Unit</th>
        <th scope="col">Price</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do | food | %>
       <tr>
        <th scope="row"> <%= food.name %></th>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td>
          <%= button_to "Delete", "foods/#{food.id}" , method: :delete, class: "btn border-danger text-danger" %>
        </td>
       </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h2>Add a new food</h2>

<%= form_with model: @food, url: foods_path do |f| %>

    <div class="field">
    <%= f.label :name, class:"mt-2" %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Apple" %>
  </div>

  <div class="field">
    <%= f.label :measurement_unit, class:"mt-2" %><br />
    <%= f.text_field :measurement_unit, autofocus: true, autocomplete: "measurement_unit", class: "form-control", placeholder: "K.g/g" %>
  </div>

  <div class="field">
    <%= f.label :price , class:"mt-2" %>
    <%= f.text_field :price, autocomplete: "price" , class: "form-control", placeholder: "LE/$" %>
  </div>

  <div class="actions">
    <%= f.submit "Add food", class: "mt-4 btn btn-success" %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center mt-4">
  <h1>Welcome to our Recipe App ✨</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
   <%= render partial: "shared/navbar"%>
   <%= render partial: "shared/flash"%>
   <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/recipe_foods/edit.html.erb
<h2>Edit quantity</h2>

<%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe.id, @recipe_food.id), method: :patch do |f| %>
  <div class="field">
    <%= f.label :quantity, class:"mt-2" %><br />
    <%= f.number_field :quantity, autofocus: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Update quantity", class: "mt-4 btn btn-success" %>
  </div>
<% end %>

app/views/recipe_foods/new.html.erb
<h2>Add a new ingredient</h2>

<%= form_with model: @ingredient, url: recipe_recipe_foods_path(@recipe.id) do |f| %>
  <div class="field">
    <%= f.label :quantity, class:"mt-2" %><br />
    <%= f.number_field :quantity, autofocus: true, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :food_id, class:"mt-2" %><br />
    <%= f.select :food_id, options_from_collection_for_select(@available_foods, 'id', 'name'), {}, { class: "form-control" }%>
  </div>

  <div class="actions">
    <%= f.submit "Add ingredient", class: "mt-4 btn btn-success" %>
  </div>
<% end %>

app/views/recipes/index.html.erb
 <div class="d-flex justify-content-end">
    <%= link_to "Add recipe", "recipes/new", class: "btn btn-success"%>
  </div>
<% if @recipes.any? %>
  <ul class="container">
    <% @recipes.each do |recipe| %>
      <%= render partial: "shared/recipe_card", locals: {recipe: recipe} %>
    <% end %>
  </ul>
<% else %>
  <div class="card mt-4">
    <div class="card-body">
      <p class="card-text">You don't have any recipes.</p>
    </div>
  </div>
<% end %>

app/views/recipes/new.html.erb
<h2>Add a new recipe</h2>

<%= form_with model: @recipe, url: recipes_path do |f| %>

    <div class="field">
    <%= f.label :name, class:"mt-2" %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "simple dish" %>
  </div>

  <div class="field">
    <%= f.label :preparation_time, class:"mt-2" %><br />
    <%= f.text_field :preparation_time, autofocus: true, class: "form-control", placeholder: "1h" %>
  </div>

  <div class="field">
    <%= f.label :cooking_time, class:"mt-2" %><br />
    <%= f.text_field :cooking_time, autofocus: true, class: "form-control", placeholder: "3h" %>
  </div>

  <div class="field">
    <%= f.label :description , class:"mt-2" %>
    <%= f.text_area :description, autocomplete: "description" , class: "form-control", placeholder: "steps here..." %>
  </div>

  <div class="form-check">
    <%= f.label :public ,class: "form-check-label"  %>
    <%= f.check_box :public, class: "form-check-input" %>
  </div>

  <div class="actions">
    <%= f.submit "Add recipe", class: "mt-4 btn btn-success" %>
  </div>
<% end %>

app/views/recipes/public_recipes.html.erb
<h2> Public Recipes</h2>

<% @recipes.each do |recipe| %>
<li class="card mt-4 bg-light">
  <div class="card-body d-flex justify-content-between">
    <div>
      <h3 class="card-title">
        <%= link_to recipe.name, recipe_path(recipe.id), class:"text-decoration-none" %>
      </h3>
      <p class="card-text"> By: <%= recipe.user.name %></p>
    </div>
    <div>
      <p> Total food items: <%= recipe.foods.length %> </p>
      <p> Total price: <%= recipe.total_price %> $ </p>
    </div>
  </div>
</li>
<% end %>

app/views/recipes/show.html.erb
<h2 class="mt-4"><%= @recipe.name %></h2>
<p>Preparation Time: <%= @recipe.preparation_time %></p>
<p>Cooking Time: <%= @recipe.cooking_time %></p>
<p><%= @recipe.description %></p>

<% if can? :manage, @recipe %>
<% if @recipe.public %>
  <%= button_to "Make private", toggle_public_path(@recipe.id), method: :patch, class: "btn btn-danger"  %>
<% else %>
  <%= button_to "Make public", toggle_public_path(@recipe.id), method: :patch, class: "btn btn-success"  %>
<% end %>
<% end %>

<div class="table-responsive mt-4">
<% if can? :manage, @recipe %>
<div class="d-flex justify-content-start">
  <%= link_to "Generate Shopping List", new_recipe_recipe_food_path(@recipe.id), class: "btn btn-success"%>
  </div>

  <div class="d-flex justify-content-end">
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id), class: "btn btn-success"%>
  </div>
  <% end %>

  <table class="table table-light table-bordered mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <% if can? :manage, @recipe %>
        <th scope="col">Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do | ingredient | %>
       <tr>
        <th scope="row"> <%= ingredient.food.name %> </th>
        <td><%= ingredient.quantity %> <%= ingredient.food.measurement_unit %></td>
        <td> <%= ingredient.food.price * ingredient.quantity %></td>
        <% if can? :manage, @recipe %>
        <td class="d-flex">
          <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe.id, ingredient.id), class: "btn border-danger text-danger" %>
          <%= button_to "Delete", recipe_recipe_food_path(@recipe.id, ingredient.id) , method: :delete, class: "ms-2 btn border-danger text-danger" %>
        </td>
        <% end %>
       </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
<div class="alert alert-info" role="alert">
  <%= flash[:notice]%>
</div>
<% end %>

<% if flash[:alert]%>
<div class="alert alert-warning" role="alert">
  <%= flash[:alert]%>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">RecipeApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if @current_user %>
          <li class="nav-item">
            <%= link_to "My Recipes", recipes_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "My Food", foods_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "public recipes", "/public_recipes", class: "nav-link"%>
          </li>
            <li class="nav-item">
            <%= link_to "shopping list", shopping_list_path , class: "nav-link"%>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if @current_user %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path , data: { method: :delete }, class: "nav-link"  %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", '/users/sign_in', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", '/users/sign_up', class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_recipe_card.html.erb
<li class="card mt-4 bg-light">
  <div class="card-body">
    <h3 class="card-title">
      <%= link_to recipe.name, recipe_path(recipe.id), class:"text-decoration-none" %>
    </h3>
    <p class="card-text"><%= truncate(recipe.description, length: 70, separator: ' ') %></p>
    <%= button_to "Delete", recipe_path(recipe.id), method: :delete, class: "btn border-danger text-danger"%>
  </div>
</li>

app/views/shopping_list/index.html.erb
<h2> shopping list </h2>
<div>
<p>Amount of foods items to buy :  <%= @foods.length %> </p>
<p>Total value of foods needed : <%= @total_price %> $ </p>
</div>
<div class="table-responsive mt-4">
  <table class="table table-light table-bordered mt-4">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">price</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do | ingredient | %>
       <tr>
        <th scope="row"> <%= ingredient.name %> </th>
        <td><%= ingredient.total_quantity_recipes %> <%= ingredient.measurement_unit %></td>
        <td> <%= ingredient.price * ingredient.total_quantity_recipes %></td>
       </tr>
      <% end %>
    </tbody>
  </table>
</div>